version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: chat-app/Dockerfile
    ports:
      - "3000:80"  # Map port 80 in the container (Nginx) to port 3000 on the host
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    env_file:
      - .env.local
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
