# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: $DOCKER_USER/backend-image:latest  # Updated to use Docker Hub path
          env:
            - name: ENVIRONMENT
              value: "kubernetes"  # Hardcoded value
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets  # Name of the secret
                  key: MONGO_URI     # Specific key in the secret
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets  # Name of the secret
                  key: OPENAI_API_KEY  # Specific key in the secret
            - name: SERPER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SERPER_API_KEY
            - name: TICKETMASTER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: TICKETMASTER_API_KEY
            - name: AMADEUS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AMADEUS_API_KEY
            - name: AMADEUS_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AMADEUS_API_SECRET
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GOOGLE_CLIENT_ID
          ports:
            - containerPort: 5001
---
# Backend Service (ClusterIP)
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP  # Exposes the backend service internally within the cluster
